# Generated by Django 5.2.3 on 2025-06-19 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='datasets/')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadisticas', models.JSONField()),
                ('grafico', models.ImageField(null=True, upload_to='plots/')),
                ('conjunto_datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analisis.conjuntodatos')),
            ],
        ),
    ]
